baseURL = "https://kraig.app/"
languageCode = "en-gb"
title = "Kraig Walker"
assetDir = "/"
disableHugoGeneratorInject = true

[params]
themeColor = "#5856d6"
description = "Kraig Walker is a Front End Developer based in Glasgow, specializing in deliverability and accessible new User Interface ideas with the Web Platform."